name: label-on-release-pr

on:
  pull_request:
    branches:
      - "main"

jobs:
  label-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add omit-release-notes label
        if: github.event.pull_request.head.ref == 'develop'
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['omit-release-notes']
            })
          token: ${{ secrets.GITHUB_TOKEN }}
