name: Add release label

on:
  pull_request:
    branches:
      - "main"

jobs:
  label-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Label Release
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['release']
            })
          token: ${{ secrets.GITHUB_TOKEN }}
